title: 'Producer '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7664277
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#082439'
    - '#5E7A8F'
    - '#47667A'
    - '#FFFFFF'
    - '#D5DBDE'
  rhythmicContrast: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
name: AshHasen
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.114098
layout_spectrum: 0.4701314
