title: 'Producer '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8501611
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#5F87AD'
    - '#243748'
    - '#97BFDB'
    - '#586259'
  rhythmicContrast: 1
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: AshHasen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 1
